export const creditPackages = [
  {
    id: 1,
    name: 'Starter',
    price: 999,
    credits: 100,
    bonus: 0,
    baseCredits: 100,
    savings: 0,
    popular: false,
    bestValue: false,
  },
  {
    id: 2,
    name: 'Popular',
    price: 1999,
    credits: 250,
    bonus: 50,
    baseCredits: 200,
    savings: 25,
    popular: true,
    bestValue: false,
  },
  {
    id: 3,
    name: 'Premium',
    price: 3999,
    credits: 600,
    bonus: 150,
    baseCredits: 450,
    savings: 33,
    popular: false,
    bestValue: false,
  },
  {
    id: 4,
    name: 'VIP',
    price: 7999,
    credits: 1400,
    bonus: 400,
    baseCredits: 1000,
    savings: 40,
    popular: false,
    bestValue: true,
  },
  {
    id: 5,
    name: 'Ultimate',
    price: 14999,
    credits: 3200,
    bonus: 1200,
    baseCredits: 2000,
    savings: 60,
    popular: false,
    bestValue: false,
  },
];

export function getPackById(id: number) {
  return creditPackages.find((p) => p.id === id) ?? null;
}
