export interface LanguageOption {
  value: string;
  label: string;
  disable?: boolean;
  fixed?: boolean;
  [key: string]: string | boolean | undefined;
}

export const LANGUAGES: LanguageOption[] = [
  { value: 'english', label: 'English' },
  { value: 'french', label: 'French' },
  { value: 'spanish', label: 'Spanish' },
  { value: 'german', label: 'German' },
  { value: 'italian', label: 'Italian' },
  { value: 'portuguese', label: 'Portuguese' },
  { value: 'russian', label: 'Russian' },
  { value: 'japanese', label: 'Japanese' },
  { value: 'korean', label: 'Korean' },
  { value: 'chinese', label: 'Chinese' },
  { value: 'arabic', label: 'Arabic' },
  { value: 'hindi', label: 'Hindi' },
  { value: 'dutch', label: 'Dutch' },
  { value: 'swedish', label: 'Swedish' },
  { value: 'norwegian', label: 'Norwegian' },
  { value: 'danish', label: 'Danish' },
  { value: 'finnish', label: 'Finnish' },
  { value: 'polish', label: 'Polish' },
  { value: 'czech', label: 'Czech' },
  { value: 'hungarian', label: 'Hungarian' },
  { value: 'romanian', label: 'Romanian' },
  { value: 'bulgarian', label: 'Bulgarian' },
  { value: 'greek', label: 'Greek' },
  { value: 'turkish', label: 'Turkish' },
  { value: 'hebrew', label: 'Hebrew' },
  { value: 'thai', label: 'Thai' },
  { value: 'vietnamese', label: 'Vietnamese' },
  { value: 'indonesian', label: 'Indonesian' },
  { value: 'malay', label: 'Malay' },
  { value: 'filipino', label: 'Filipino' },
  { value: 'urdu', label: 'Urdu' },
  { value: 'bengali', label: 'Bengali' },
  { value: 'persian', label: 'Persian' },
  { value: 'ukrainian', label: 'Ukrainian' },
  { value: 'belarusian', label: 'Belarusian' },
  { value: 'serbian', label: 'Serbian' },
  { value: 'croatian', label: 'Croatian' },
  { value: 'slovenian', label: 'Slovenian' },
  { value: 'slovak', label: 'Slovak' },
  { value: 'lithuanian', label: 'Lithuanian' },
  { value: 'latvian', label: 'Latvian' },
  { value: 'estonian', label: 'Estonian' },
  { value: 'icelandic', label: 'Icelandic' },
  { value: 'irish', label: 'Irish' },
  { value: 'welsh', label: 'Welsh' },
  { value: 'scottish_gaelic', label: 'Scottish Gaelic' },
  { value: 'catalan', label: 'Catalan' },
  { value: 'basque', label: 'Basque' },
  { value: 'galician', label: 'Galician' },
  { value: 'swahili', label: 'Swahili' },
  { value: 'yoruba', label: 'Yoruba' },
  { value: 'zulu', label: 'Zulu' },
  { value: 'afrikaans', label: 'Afrikaans' },
  { value: 'amharic', label: 'Amharic' },
  { value: 'somali', label: 'Somali' },
  { value: 'hausa', label: 'Hausa' },
  { value: 'igbo', label: 'Igbo' },
  { value: 'mongolian', label: 'Mongolian' },
  { value: 'kazakh', label: 'Kazakh' },
  { value: 'uzbek', label: 'Uzbek' },
  { value: 'kyrgyz', label: 'Kyrgyz' },
  { value: 'tajik', label: 'Tajik' },
  { value: 'turkmen', label: 'Turkmen' },
  { value: 'azerbaijani', label: 'Azerbaijani' },
  { value: 'georgian', label: 'Georgian' },
  { value: 'armenian', label: 'Armenian' },
  { value: 'albanian', label: 'Albanian' },
  { value: 'macedonian', label: 'Macedonian' },
  { value: 'bosnian', label: 'Bosnian' },
  { value: 'montenegrin', label: 'Montenegrin' },
  { value: 'kosovan', label: 'Kosovan' },
];
